CREATE DATABASE WEEK_3_DB;

CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR (200)
);

INSERT INTO USERS VALUES (1, 'Alex');
INSERT INTO USERS VALUES (2, 'Bob');

SELECT * FROM USERS;
